# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  userapi:
    image: userapi
    build:
      context: .
      dockerfile: ProjectExchange.API/Services/User/API/Dockerfile
    ports:
      - "5000:5000"
  productapi:
    image: productapi
    build:
      context: .
      dockerfile: ProjectExchange.API/Services/Product/API/Dockerfile
    ports:
      - "5002:5002"
  adminapi:
    image: adminapi
    build:
      context: .
      dockerfile: ProjectExchange.API/Services/Admin/API/Dockerfile
    ports:
      - "5004:5004"
  exchangeapi:
    image: exchangeapi
    build:
      context: .
      dockerfile: ProjectExchange.API/ApiGateways/ExchangeGateway/Dockerfile
    ports:
      - "5010:5010"

