# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  userapi:
    image: userapi
    build:
      context: .
      dockerfile: Services/User/API/Dockerfile
    ports:
      - "5000:5000"
  productapi:
    image: productapi
    build:
      context: .
      dockerfile: Services/Product/API/Dockerfile
    ports:
      - "5002:5002"
